---
- hosts: configsvr 
  remote_user: "{{ ansible_user }}"
  vars: 
    key_content: "{{ lookup('aws_ssm', '/cloudj/cloudiac/ansible/ssh-key', region='us-west-2') }}"
  gather_facts: no
  become: true

  tasks:
    - name: Wait 300 seconds, but only start checking after 20 seconds
      wait_for_connection:
        delay: 20
        timeout: 300

    - name: install packages
      yum:
        name: 
          - git
          - python3
          - yum-utils
          - awscli

    - name: save key to file
      template:
        src:  ./key.j2
        dest: /root/ob.pem
        mode: '0400'
   
    - name: generate cluster config 
      template:
        src: ./cluster.j2
        dest: /root/cluster.yaml
        mode: '0644'
    
    - name: read cluster file
      command: cat /root/cluster.yaml
      register: cls 
      
    - name: show cluster config file
      debug:
        msg: "{{ cls.stdout_lines }}"

    - name: repo 
      command: yum-config-manager --add-repo https://mirrors.aliyun.com/oceanbase/OceanBase.repo 

    - name: install ob 
      yum:
        name: ob-deploy

    - name: deploy cluster
      command: obd cluster deploy c1 -c /root/cluster.yaml

    - name: cluster list
      command: obd cluster list 
      register: out

    - name: show cluster status
      debug: 
        msg: "{{ out.stdout_lines }}"